version: "3"
services:
  database:
    image: "postgres:10.5"
    container_name: "db"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/00000000000001_create_persons/up.sql:/docker-entrypoint-initdb.d/init.sql
